  version: '3.8'

  services:
    web:
      image: nginx:alpine
      ports:
        - "80:80"
      volumes:
        - ./html:/usr/share/nginx/html
      depends_on:
        - app

    app:
      image: python:3.9-slim
      working_dir: /app
      volumes:
        - ./app:/app
      command: python app.py
      ports:
        - "5000:5000"
